- type: antag
  id: SoulbreakerAntag
  name: soulbreaker-ghost-role-name
  antagonist: true
  objective: roles-antag-soulbreaker-objective
  setPreference: false
  guides: [ SoulbreakersGuide ]
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 180000 # 50 hours
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 54000 # 15 hours

- type: antag
  id: SoulbreakerAssistantAntag
  name: soulbreaker-assistant-ghost-role-name
  antagonist: false
  objective: roles-antag-soulbreaker-assistant-objective
  setPreference: false
  guides: [ SoulbreakersGuide ]
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 45000 # 12,5 hours
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 13500 # 3,75 hours
